# Generated by Django 4.2.3 on 2023-07-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comment',
            new_name='nameTask',
        ),
    ]
