# Generated by Django 4.2.3 on 2023-07-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_comment_task_nametask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='nameTask',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
